# -*- coding: utf-8 -*-
"""Image Background Removal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JylIyC_RpQ8stJqzRMhYALyP512FCfuF
"""

!pip install rembg gradio pillow onnxruntime

import gradio as gr
from rembg import remove
from PIL import Image, ImageDraw
import io

def create_checkerboard(size, square_size=40):
    width, height = size
    bg = Image.new("RGBA", size, (255, 255, 255, 255))
    draw = ImageDraw.Draw(bg)

    for y in range(0, height, square_size):
        for x in range(0, width, square_size):
            color = (220, 220, 220, 255) if (x//square_size + y//square_size) % 2 == 0 else (255, 255, 255, 255)
            draw.rectangle([x, y, x + square_size, y + square_size], fill=color)
    return bg


def remove_background(input_image):
    img_bytes = io.BytesIO()
    input_image.save(img_bytes, format="PNG")
    img_bytes = img_bytes.getvalue()

    output_bytes = remove(img_bytes)
    cutout = Image.open(io.BytesIO(output_bytes)).convert("RGBA")

    cb = create_checkerboard(input_image.size)

    final_img = Image.new("RGBA", input_image.size)
    final_img.paste(cb, (0, 0))
    final_img.paste(cutout, (0, 0), cutout)

    png_path = "/tmp/output.png"
    final_img.save(png_path, "PNG")

    return final_img, png_path

with gr.Blocks() as interface:

    gr.Markdown(
        """
        <div style="text-align: center; margin-bottom: 20px;">
            <h1 style="font-size: 42px; font-weight: 900; color: #1a73e8;">
                🖼️ AI Background Remover
            </h1>
            <h3 style="font-size: 20px; font-weight: 500;">
                Remove your image background instantly with clean checkerboard output!
            </h3>
        </div>
        """
    )

    with gr.Row():
        input_img = gr.Image(
            type="pil",
            label="Upload Image",
            width=700,
            height=700
        )

    remove_btn = gr.Button("Remove Background")

    with gr.Row():
        output_preview = gr.Image(
            type="pil",
            label="Final Output Preview",
            width=700,
            height=700
        )
        download_png = gr.File(label="Download PNG")

    remove_btn.click(
        remove_background,
        inputs=input_img,
        outputs=[output_preview, download_png]
    )

interface.launch(share=True)

